title: BobsterJS Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.bobsterjs.ml/
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#CC0033"
  systems:
    - name: BobsterJS
      category: Websites
    - name: Weather
      category: Websites
    - name: Clock
      category: Websites
    - name: Stopwatch
      category: Websites
    - name: Social
      category: Websites
    - name: RE1
      category: Data Stores
    - name: NE1
      category: Data Stores
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/bobsterjs-light-blue.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#e8611e"
  notice: "#1eb2e8"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#33CC33"
  categories:
    - name: Websites
      closed: false
      untitled: false
    - name: Data Stores
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: true
